---
title: "Prediction"
author: "yunchen"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(MASS)
library(e1071)
library(caret)
library(tidyverse)

```



```{r pressure, echo=FALSE}
data<-read.csv("predictors_nodes.csv")
#remove columns that I don't need

data <- data[,1:16]
data <- data[,-grep("community_id|week|motif_4_4|motif_4_5",colnames(data))] #remove sparse variables
data<-filter(data, next_y != 0)
brmse <- sqrt(sum((data$y - data$next_y)^2)/length(data$next_y)) #baseline model rmse
bmse <- sum((data$y - data$next_y)^2)/length(data$next_y)
brmse
```


```{r glmnet}
set.seed(2)
fitControl <- trainControl(method = "LOOCV")
expand.grid<- expand.grid(
  alpha = 0:1,
  lambda = seq(0.0001, 1, length = 100)
)

glmnetm <- train(next_y~., data = data, method = "glmnet", trControl = fitControl, tuneGrid = expand.grid)
mean(glmnetm$results[,3]) 
#cv_rmse
#3.092467 pca
#3.104849 without pca
```

```{r bagEarth BEST MODEL1}


#specify the cross-validation method
ctrl <- trainControl(method = "LOOCV")
set.seed(7)
#fit a regression model and use LOOCV to evaluate performance
bagEarthm <- train(next_y~., data = data, method = "bagEarth", trControl = ctrl,tuneLength = 10,preProcess=c('scale','pca'))

#view summary of LOOCV               
mean(bagEarthm$results[,3]) 
#cv_rmse
# 2.476049 without pca  
#5.792996 with pca
```

```{r cubist BEST MODEL2}

#specify the cross-validation method
ctrl <- trainControl(method = "LOOCV")

#fit a regression model and use LOOCV to evaluate performance
cubistm <- train(next_y~., data = data, method = "cubist", trControl = ctrl, tuneLength = 15,preProcess=c('scale','pca'))

mean(cubistm$results[,3])              
#2.659203 without pca
#2.889244 with pca
```

```{r gradient boosting machine}
set.seed(4)
fitControl <- trainControl(method = "LOOCV")
gbmGrid <-  expand.grid(interaction.depth = c(1, 5, 9), 
                        n.trees = (1:30)*50, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)
gbmFit <-train(next_y~., data = data, method = "gbm", trControl = fitControl,tuneGrid = gbmGrid, preProcess=c('scale','pca'))
#pred<-predict(gbmFit, newdata = test)
#RMSE(pred,test$next_y)
mean(gbmFit$results[,5])
#2.662519 without pca
#2.955945 with pca

```

```{r Partial Least Squares}
set.seed(5)
fitControl <- trainControl(method = "LOOCV")

plsFit <-train(next_y~., data = data, method = "pls", trControl = fitControl, preProcess=c('scale','pca') )
mean(plsFit$results[,2])
#3.394098 with pca
#3.472536 without pca
```



```{r L2 Regularized Support Vector Machine (dual) with Linear Kernel}
set.seed(5)
fitControl <- trainControl(method = "LOOCV")

L2Fit <-train(next_y~., data = data, method = "svmLinear3", trControl = fitControl  )
print(L2Fit)
#RMSE(pred,test$next_y)
mean(L2Fit$results[,3])
#3.19221 with pca
#4.797971 without
```


```{r}
set.seed(2)
fitControl <- trainControl(method = "LOOCV")

lm <- train(next_y~., data = data, method = "lm", trControl = fitControl, tuneLength = 5, preProcess=c('scale','pca'))

lm$results
#3.051659    with pca
#11.09236   without pca
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
